### ISSUE TITLE
Need licensing information

### ISSUE THREAD

**Issue by Rho-n** [2Max4/Network_Analysis#30]
I could find no licensing information. Either a common license file should be created, or at least ithe license should be included in the README.md.

**Comment by 2Max4** [comment]
Hey @Rho-n ,
Thanks for the input! Which type of license would you suggest? Feel free to make a PR with added license

**Comment by miltonArango** [comment]
Addresed in https://github.com/2Max4/Network_Analysis/pull/31

**Comment by 2Max4** [comment]
Closed - see PR #31
